name: .NET Core

on:
  push:
    branches: [ github-ci ]
  pull_request:
    branches: [ github-ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env: 
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build ./WindowsAzure/WindowsAzure.csproj --framework netstandard1.3 --configuration Release --no-restore
        dotnet build ./WindowsAzure.Tests/WindowsAzure.Tests.csproj --framework netcoreapp3 --configuration Release --no-restore
    - name: Test
      run: dotnet test --framework netcoreapp3 --no-restore --verbosity normal
    - name: Publish
      run: |
        dotnet pack ./WindowsAzure/WindowsAzure.csproj --configuration Release --no-restore --no-build --no-symbols true -p:TargetFramworks=netstandard1.3
        dotnet nuget push ./WindowsAzure/bin/Release/*.nupkg --skip-duplicate --no-symbols true
